### ISSUE TITLE
Is this supposed to be open to view

### ISSUE THREAD

**Issue by tWizT3ddreaMr** [snowgears/Shop#2]
Just out of concern for you intellectual property. This doesn't seem to be a private repository.
And if it is meant to be open, might we do pull requests to help patch some issues.

**Comment by BillyGalbreath** [comment]
It was private last I saw :O

**Comment by tWizT3ddreaMr** [comment]
Yeah, no, I can clearly see everything. I stumbled on it by chance, because I looked at snowgear's profile

**Comment by snowgears** [comment]
I opened it up publicly. Please feel free to submit pull requests as you see fit and I will review them!
