### ISSUE TITLE
[Enhancement] Buy/Sell additions

### ISSUE THREAD

**Issue by LogGits** [snowgears/Shop#5]
For the Combo system, It would be nice if you could left click to sell, right click to buy or inverse (something toggleable in the config).

It's also be really convenient to have some sort of "buy stack" with a confirmation. E.g. shift, left click to open a "buy stack" confirmation screen where the amount would be within 2-64 depending on what they can afford and how many items are left.

E.g. if it's an admin shop it'd just be 2-64 depending on how much they can afford.

**Comment by snowgears** [comment]
Closing and adding to correct issue repo: 
https://github.com/snowgears/shopbugs/issues/158
https://github.com/snowgears/shopbugs/issues/159
