### ISSUE TITLE
[Enhancement] Punch for more info

### ISSUE THREAD

**Issue by LogGits** [snowgears/Shop#6]
A feature that would be nice is some form of "Punch the invis armorstand to get more info" e.g. if the player punches the invis armorstand and the armorstand is a shop armorstand e.g. persistentdata or nbt stuffs, send the player a message talking about the Item:
"This item is a [item]" (with the hover similar to punching the chest)

**Comment by snowgears** [comment]
This already happens by clicking on the chest.

**Comment by LogGits** [comment]
Yes I know, i've been testing with a few players, only mentioning "What would you do to get more info?" and 8/11 people punched the invis armorstand/item entity. It's a form of intuitive information delivery.
