### ISSUE TITLE
Add new itemframe displaytype with configurable options

### ISSUE THREAD

**Issue by LogGits** [snowgears/Shop#7]
So i found out a while back that itemframes can be positioned really weirdly as per:
https://www.youtube.com/watch?v=FljPjDczTU8

That coupled with 1.16+ itemframe mechanics that allow invisible itemframes. You may be able to do some crazy things with it :)

**Comment by snowgears** [comment]
I will definitely be adding this as a DisplayType in a future version. I appreciate the suggestion!

**Comment by snowgears** [comment]
Closing and moving over to correct issue repo: https://github.com/snowgears/shopbugs/issues/156
