### ISSUE TITLE
Player heads glitching on floating item above shop chest

### ISSUE THREAD

**Issue by fahlur** [snowgears/Shop#8]
I am having this issue where a player head on a shop displaying above the shop chest will sometimes be a bunch of that head at one time like it duplicated. Then all of a sudden they will disappear like it changed modes without player interaction. Ill try to provide screenshots when it happens next. It seems to be random.

**Comment by snowgears** [comment]
Yeah, screenshots would be very helpful. Do you mean you are selling a playerhead through a shop?

**Comment by snowgears** [comment]
Closing and moving over to correct issue repo: https://github.com/snowgears/shopbugs/issues/157
